<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="0" total="5" passed="0">
  <reporter-output>
    <line>
      <![CDATA[chrome launched]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="21936" started-at="2018-06-20T07:15:21Z" finished-at="2018-06-20T07:15:43Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="21936" started-at="2018-06-20T07:15:21Z" finished-at="2018-06-20T07:15:43Z">
      <class name="Com.actitime.script.TaskTest">
        <test-method status="SKIP" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:Com.actitime.script.TaskTest@34c75a]" name="setUp" is-config="true" duration-ms="0" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createCustomer()[pri:0, instance:Com.actitime.script.TaskTest@34c75a]" name="createCustomer" duration-ms="3" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method status="SKIP" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Com.actitime.script.TaskTest@34c75a]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="deleteCustomer()[pri:0, instance:Com.actitime.script.TaskTest@34c75a]" name="deleteCustomer" duration-ms="0" started-at="2018-06-20T12:45:43Z" depends-on-methods="Com.actitime.script.TaskTest.createCustomer" finished-at="2018-06-20T12:45:43Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TaskTest.deleteCustomer()[pri:0, instance:Com.actitime.script.TaskTest@34c75a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TaskTest.deleteCustomer()[pri:0, instance:Com.actitime.script.TaskTest@34c75a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="SKIP" signature="CreateNeewProject()[pri:0, instance:Com.actitime.script.TaskTest@34c75a]" name="CreateNeewProject" duration-ms="0" started-at="2018-06-20T12:45:43Z" depends-on-methods="Com.actitime.script.TaskTest.createCustomer, Com.actitime.script.TaskTest.deleteCustomer" finished-at="2018-06-20T12:45:43Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TaskTest.CreateNeewProject()[pri:0, instance:Com.actitime.script.TaskTest@34c75a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TaskTest.CreateNeewProject()[pri:0, instance:Com.actitime.script.TaskTest@34c75a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateNeewProject -->
      </class> <!-- Com.actitime.script.TaskTest -->
      <class name="Com.actitime.script.LoginTest">
        <test-method status="FAIL" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:Com.actitime.script.LoginTest@1efea79]" name="setUp" is-config="true" duration-ms="0" started-at="2018-06-20T12:45:21Z" finished-at="2018-06-20T12:45:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://127.0.0.1/login.do]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[chrome not reachable
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.01 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'V1550-5493QR1', ip: '127.0.0.1', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9), userDataDir=C:\Users\DELL\AppData\Local\Temp\scoped_dir1056_24204}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=67.0.3396.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: a8fdc39f588b21f6a7b6a85dfa7af2d3]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.01 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'V1550-5493QR1', ip: '127.0.0.1', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9), userDataDir=C:\Users\DELL\AppData\Local\Temp\scoped_dir1056_24204}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=67.0.3396.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: a8fdc39f588b21f6a7b6a85dfa7af2d3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:969)
	at Com.actitime.generic.BaseLib.setUp(BaseLib.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
            <line>
              <![CDATA[chrome launched]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="validLogin()[pri:1, instance:Com.actitime.script.LoginTest@1efea79]" name="validLogin" duration-ms="2" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method status="SKIP" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Com.actitime.script.LoginTest@1efea79]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:Com.actitime.script.LoginTest@1efea79]" name="setUp" is-config="true" duration-ms="0" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="invalidLogin()[pri:2, instance:Com.actitime.script.LoginTest@1efea79]" name="invalidLogin" duration-ms="1" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLogin -->
        <test-method status="SKIP" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Com.actitime.script.LoginTest@1efea79]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-06-20T12:45:43Z" finished-at="2018-06-20T12:45:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Com.actitime.script.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
